[build]
builder = "dockerfile"
dockerfilePath = "biodiagnostico_app/Dockerfile"
watchPatterns = ["biodiagnostico_app/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[services]]
port = 8080
